add webidl as a possible deliverable
w3c/webappswg pull request #52
Opened 2021-06-07 09:27 UTC by siusin

To address comments from #49 and [strategy#269](https://github.com/w3c/strategy/issues/269#issuecomment-854072755).

- Add WebIDL to the Deliverables section;
- Remove the WebSec IG from Coordination;
- Switch to the latest charter template for the  Success Criteria section and the Coordination section;

2021-06-07 09:53 UTC, sideshowbarker approved these changes

2021-06-07 09:54 UTC, sideshowbarker commented
(holding off on merging until others have reviewed)

2021-06-07 16:46 UTC, plehegar requested changes

2021-06-07 16:46 UTC, plehegar commented on charter/draft-charter-2021.html
> +            "https://www.w3.org/2020/Process-20200915/#rec-pr">Proposed
```suggestion
            "https://www.w3.org/Consortium/Process/#rec-pr">Proposed
```

2021-06-07 16:46 UTC, plehegar commented on charter/draft-charter-2021.html
> +            "https://www.w3.org/2020/Process-20200915/#Consensus">Consensus</a> of the Working Group members, the Group may bring the following WHATWG Review Drafts from W3C Candidate Recommendation
```suggestion
            "https://www.w3.org/Consortium/Process/#Consensus">Consensus</a> of the Working Group members, the Group may bring the following WHATWG Review Drafts from W3C Candidate Recommendation to Proposed Recommendation, in accordance with the <a href="https://www.w3.org/2021/03/WHATWG-W3C-MOU.html">WHATWG-W3C Memorandum of Understanding</a>: <!-- @@update with latest MOU link once available -->
```

2021-06-08 07:13 UTC, marcoscaceres approved these changes
With @plehegar suggestions, lgtm.

2021-06-08 07:14 UTC, marcoscaceres commented
@siusin, before merging, could you kindly please run:

```
tidy -config tidyconfig.txt -o charter/draft-charter-2021.html charter/draft-charter-2021.html
```

Thanks 🙏

2021-06-08 07:25 UTC, siusin commented
@marcoscaceres @plehegar 
Done. Thanks!

2021-06-08 19:49 UTC, plehegar approved these changes

2021-06-09 00:08 UTC, merged